# Generated by Django 4.0.6 on 2022-10-18 22:57

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_address_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=base.models.upload_profile),
        ),
    ]
