# Generated by Django 4.0.6 on 2022-10-18 23:04

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_user_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, default='file/profile/user default.png', null=True, upload_to=base.models.upload_profile),
        ),
    ]
