# Generated by Django 4.0.6 on 2022-10-18 23:07

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_user_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(default='file/profile/user default.png', upload_to=base.models.upload_profile),
        ),
    ]
