# Generated by Django 4.0.6 on 2022-10-19 00:13

import base.models
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_user_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=django_resized.forms.ResizedImageField(crop=None, default='profile/user default.png', force_format=None, keep_meta=True, quality=-1, scale=None, size=[500, 300], upload_to=base.models.upload_profile),
        ),
    ]
